### ISSUE TITLE
ee-beta-labs.play-with-docker.com provides linux only cluster

### ISSUE THREAD

**Issue by ghost** [dockersamples/docker-fifth-birthday#16]
Hello,
Please see title.

Thanks in advance,
Naseem

**Comment by ghost** [comment]
Hi,

Now it says that no more sessions are available.
I suppose they will only be available, and will have a window node each, during the birthday party, if this is the case forgive me for my ignorance and close this issue.

Thanks,
Naseem

**Comment by ManoMarks** [comment]
Are you at a birthday event right now? If so, which one? That's not the site that you should be directed to.

**Comment by ghost** [comment]
Hello!
Not atm, but in a few hours yes. Montreal.

I was following the exercises included in this repo before the big party as I will be helping out.
Since the link for the Linux 101 environment worked, I thought that the link to the Windows 101 would work as well.

I know we will also be provided an environment by submitting our info to do the "Deploying Multi-OS applications with Docker EE"

Thanks,
N

**Comment by ManoMarks** [comment]
Thanks, I found those links and removed them. The workshop organizers should provide a URL for you to access the environment.

**Comment by ghost** [comment]
Great, thank you.
