### ISSUE TITLE
 movieplex7 application URL

### ISSUE THREAD

**Issue by sanjayshrestha** [dockersamples/docker-fifth-birthday#21]
This is related to Modernizing Traditional Java Applications.

As per instruction, I was trying to hit movieplex7 url with 8080 port but got error however it works with designated port i.e. http://ip172-18-0-6-baoohqugera000cf87og.direct.beta-hybrid.play-with-docker.com:30364/movieplex7/faces/client/movies.xhtml

And when I tried to connect to react-client url, pages appears but could not connect to movieplex7 service. I think it might be trying to connect to 8080 port instead of 30364.

**Comment by ManoMarks** [comment]
@spara

**Comment by spara** [comment]
removed `type: LoadBalancer` and updated kubernetes manifest to use nodePort and defined the external port
