### ISSUE TITLE
 Docker for Beginners - Linux - Task2 - Query

### ISSUE THREAD

**Issue by maniSbindra** [dockersamples/docker-fifth-birthday#25]
Task 2 (https://training.play-with-docker.com/beginner-linux/#Task_2) step 1 mentions

 ```cd ~/linux_tweet_app``` 
 **where is this directory linux_tweet_app?** . I believe the files in this directory (html and png) are referenced in the dockerfile in subsequent steps.

Output from web console below
```sh
[node1] (local) root@192.168.0.28 ~
$ ls -al ~/
total 16
drwx------    1 root     root            18 Feb  8 01:20 .
drwxr-xr-x    1 root     root            57 Mar 23 14:45 ..
drwx------    3 root     root            17 Feb  8 01:20 .cache
-rw-rw-r--    1 root     root            43 Jan 17 16:42 .gitconfig
-rw-rw-r--    1 root     root          1865 Jan 17 16:42 .inputrc
-rw-rw-r--    1 root     root           185 Jan 17 16:42 .profile
drwxr-xr-x    2 root     root            61 Feb  8 01:20 .ssh
-rw-rw-r--    1 root     root            85 Jan 17 16:42 .vimrc
```

**Comment by ManoMarks** [comment]
In the first task, https://training.play-with-docker.com/beginner-linux/#Task_0 you would have cloned the repository into the current directory. Since no other tasks in between involved changing directories it would have been there.

**Comment by maniSbindra** [comment]
Sorry about that. Thanks
