### ISSUE TITLE
volume mounts in Docker for Desktop Kubernetes

### ISSUE THREAD

**Issue by DdannyB** [dockersamples/docker-fifth-birthday#34]
Hello,

Does anybody know why i cant mount files from my compose file in Kubernetes but for Docker swarm it works?
i am using the new Kubernetes feature in Docker for Desktop. The mount im trying to make is:

Volumes:

- C:\docker\appsettings.json:/app/appsettings.json

i am getting this error:

Stack.compose.docker.com "adapter" is invalid: adapter: Invalid value: "null": conversion to kube entities failed: C:\docker\appsettings.json: only absolute paths can be specified in mount source

**Comment by ManoMarks** [comment]
@DdannyB this isn't related to a specific Docker docker samples app so I'm closing it. I suggest joining the Docker Community Slack and asking questions there: https://community.docker.com/registrations/groups/4316 or in the Docker Forums: https://forums.docker.com/.
